Exploring and Cleaning Deliveries

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [19]:
df = pd.read_csv("../Data/IPL_Ball_by_Ball_2008_2022.csv")

In [20]:
df.shape

(225954, 17)

In [21]:
df.columns

Index(['ID', 'innings', 'overs', 'ballnumber', 'batter', 'bowler',
       'non-striker', 'extra_type', 'batsman_run', 'extras_run', 'total_run',
       'non_boundary', 'isWicketDelivery', 'player_out', 'kind',
       'fielders_involved', 'BattingTeam'],
      dtype='object')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225954 entries, 0 to 225953
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   ID                 225954 non-null  int64 
 1   innings            225954 non-null  int64 
 2   overs              225954 non-null  int64 
 3   ballnumber         225954 non-null  int64 
 4   batter             225954 non-null  object
 5   bowler             225954 non-null  object
 6   non-striker        225954 non-null  object
 7   extra_type         12049 non-null   object
 8   batsman_run        225954 non-null  int64 
 9   extras_run         225954 non-null  int64 
 10  total_run          225954 non-null  int64 
 11  non_boundary       225954 non-null  int64 
 12  isWicketDelivery   225954 non-null  int64 
 13  player_out         11151 non-null   object
 14  kind               11151 non-null   object
 15  fielders_involved  7988 non-null    object
 16  BattingTeam        2

dismissal_Type and fielder have null values

In [23]:
df.describe()

ID        innings          overs     ballnumber  \
count  2.259540e+05  225954.000000  225954.000000  225954.000000   
mean   8.320470e+05       1.483868       9.185679       3.619750   
std    3.379542e+05       0.503104       5.681797       1.810633   
min    3.359820e+05       1.000000       0.000000       1.000000   
25%    5.012620e+05       1.000000       4.000000       2.000000   
50%    8.297370e+05       1.000000       9.000000       4.000000   
75%    1.178395e+06       2.000000      14.000000       5.000000   
max    1.312200e+06       6.000000      19.000000      10.000000   

         batsman_run     extras_run     total_run   non_boundary  \
count  225954.000000  225954.000000  225954.00000  225954.000000   
mean        1.243523       0.066907       1.31043       0.000093   
std         1.618166       0.341470       1.60605       0.009640   
min         0.000000       0.000000       0.00000       0.000000   
25%         0.000000       0.000000       0.00000       0.000000   
50%         1.000000       0.000000       1.00000       0.000000   
75%         1.000000       0.000000       1.00000       0.000000   
max         6.000000       7.000000       7.00000       1.000000   

       isWicketDelivery  
count     225954.000000  
mean           0.049351  
std            0.216600  
min            0.000000  
25%            0.000000  
50%            0.000000  
75%            0.000000  
max            1.000000

In [24]:
df.columns

Index(['ID', 'innings', 'overs', 'ballnumber', 'batter', 'bowler',
       'non-striker', 'extra_type', 'batsman_run', 'extras_run', 'total_run',
       'non_boundary', 'isWicketDelivery', 'player_out', 'kind',
       'fielders_involved', 'BattingTeam'],
      dtype='object')

In [25]:
df["kind"].unique()

array([nan, 'caught', 'caught and bowled', 'run out', 'bowled', 'stumped',
       'lbw', 'hit wicket', 'retired hurt', 'retired out',
       'obstructing the field'], dtype=object)

In [26]:
df.loc[df["kind"] == "runout", "dismissal_type"] = "run out"

In [27]:
df.loc[(df["kind"] == "retired hurt") | (df["kind"] == "retired out"), "kind"] = "retired"

In [28]:
df["kind"].unique()

array([nan, 'caught', 'caught and bowled', 'run out', 'bowled', 'stumped',
       'lbw', 'hit wicket', 'retired', 'obstructing the field'],
      dtype=object)

In [31]:
df['batter'].unique()

array(['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal',
       'SO Hetmyer', 'R Ashwin', 'R Parag', 'TA Boult', 'OC McCoy',
       'WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pandya', 'DA Miller',
       'V Kohli', 'F du Plessis', 'RM Patidar', 'GJ Maxwell', 'MK Lomror',
       'KD Karthik', 'Shahbaz Ahmed', 'PWH de Silva', 'HV Patel',
       'JR Hazlewood', 'Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda',
       'MP Stoinis', 'E Lewis', 'KH Pandya', 'PVD Chameera', 'PK Garg',
       'Abhishek Sharma', 'RA Tripathi', 'AK Markram', 'N Pooran',
       'Washington Sundar', 'R Shepherd', 'J Suchith', 'B Kumar',
       'Umran Malik', 'JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',
       'MA Agarwal', 'LS Livingstone', 'JM Sharma', 'PN Mankad',
       'PP Shaw', 'DA Warner', 'MR Marsh', 'RR Pant', 'SN Khan',
       'R Powell', 'AR Patel', 'SN Thakur', 'Kuldeep Yadav',
       'Ishan Kishan', 'RG Sharma', 'D Brevis', 'Tilak Varma', 'TH David',
       'Ramandeep Singh', 'DR Sams', 'RD Gaikwa

In [32]:
df['bowler'].unique()

array(['Mohammed Shami', 'Yash Dayal', 'LH Ferguson', 'Rashid Khan',
       'HH Pandya', 'R Sai Kishore', 'TA Boult', 'M Prasidh Krishna',
       'YS Chahal', 'OC McCoy', 'R Ashwin', 'Mohammed Siraj',
       'JR Hazlewood', 'GJ Maxwell', 'Shahbaz Ahmed', 'HV Patel',
       'PWH de Silva', 'Mohsin Khan', 'PVD Chameera', 'KH Pandya',
       'Avesh Khan', 'Ravi Bishnoi', 'AS Joseph', 'LS Livingstone',
       'Arshdeep Singh', 'K Rabada', 'NT Ellis', 'Harpreet Brar',
       'B Kumar', 'Washington Sundar', 'Fazalhaq Farooqi', 'J Suchith',
       'Umran Malik', 'R Shepherd', 'DR Sams', 'HR Shokeen', 'JJ Bumrah',
       'M Markande', 'RP Meredith', 'Ramandeep Singh', 'KK Ahmed',
       'A Nortje', 'SN Thakur', 'MR Marsh', 'Kuldeep Yadav', 'AR Patel',
       'Mukesh Choudhary', 'Simarjeet Singh', 'MJ Santner', 'M Pathirana',
       'MM Ali', 'PH Solanki', 'S Kaul', 'MK Lomror', 'UT Yadav',
       'TG Southee', 'SP Narine', 'CV Varun', 'AD Russell', 'N Rana',
       'JO Holder', 'K Gowtham', 'M

In [34]:
df['fielders_involved'].unique()

array([nan, 'R Sai Kishore', 'Mohammed Shami', 'WP Saha', 'DA Miller',
       'R Tewatia', 'R Parag', 'YBK Jaiswal', 'SV Samson', 'R Ashwin',
       'OC McCoy', 'JC Buttler', 'V Kohli', 'KD Karthik', 'Q de Kock',
       'Mohsin Khan', 'E Lewis', 'KL Rahul', 'F du Plessis',
       'Shahbaz Ahmed', 'RM Patidar', 'AS Joseph', 'D Padikkal',
       'MA Agarwal', 'S Dhawan', 'LS Livingstone', 'JM Sharma',
       'PN Mankad', 'Washington Sundar', 'J Suchith', 'PK Garg',
       'JJ Bumrah', 'RG Sharma', 'Ishan Kishan', 'TH David', 'SN Thakur',
       'DA Warner', 'PP Shaw', 'RR Pant', 'MM Ali', 'M Pathirana',
       'DP Conway', 'GJ Maxwell', 'HH Pandya', 'MS Wade', 'MP Stoinis',
       'DJ Hooda', 'M Markande', 'Tilak Varma', 'KS Williamson',
       'B Kumar', 'T Natarajan', 'RD Chahar', 'PBB Rajapaksa', 'R Dhawan',
       'Harpreet Brar', 'AR Patel', 'A Nortje', 'R Powell', 'KH Pandya',
       'JDS Neesham', 'Rashid Khan', 'Yash Dayal', 'S Dube',
       'Shashank Singh', 'RA Tripathi', 'SW B

In [35]:
df['BattingTeam'].unique()

array(['Rajasthan Royals', 'Gujarat Titans',
       'Royal Challengers Bangalore', 'Lucknow Super Giants',
       'Sunrisers Hyderabad', 'Punjab Kings', 'Delhi Capitals',
       'Mumbai Indians', 'Chennai Super Kings', 'Kolkata Knight Riders',
       'Kings XI Punjab', 'Delhi Daredevils', 'Rising Pune Supergiant',
       'Gujarat Lions', 'Rising Pune Supergiants', 'Pune Warriors',
       'Deccan Chargers', 'Kochi Tuskers Kerala'], dtype=object)

In [38]:
df.loc[df['BattingTeam'] == 'Gujarat Lions', 'BattingTeam'] = 'Gujarat Titans'
df.loc[df['BattingTeam'] == 'Deccan Chargers', 'BattingTeam'] = 'Sunrisers Hyderabad'
df.loc[df['BattingTeam'] == 'Kings XI Punjab', 'BattingTeam'] = 'Punjab Kings'
df.loc[df['BattingTeam'] == 'Delhi Daredevils', 'BattingTeam'] = 'Delhi Capitals'
df.loc[(df['BattingTeam'] == 'Rising Pune Supergiant') | (df['BattingTeam'] == 'Pune Warriors'), 'BattingTeam'] = 'Rising Pune Supergiants'

In [39]:
df['BattingTeam'].unique()

array(['Rajasthan Royals', 'Gujarat Titans',
       'Royal Challengers Bangalore', 'Lucknow Super Giants',
       'Sunrisers Hyderabad', 'Punjab Kings', 'Delhi Capitals',
       'Mumbai Indians', 'Chennai Super Kings', 'Kolkata Knight Riders',
       'Rising Pune Supergiants', 'Kochi Tuskers Kerala'], dtype=object)

In [40]:
df['extra_type'].unique()

array([nan, 'legbyes', 'wides', 'byes', 'noballs', 'penalty'],
      dtype=object)

In [41]:
df.to_csv("../Data/deliveries_cleaned.csv", index = False)